# Generated by Django 4.1.3 on 2022-11-22 04:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='موضوع')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='قیمت')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='category.category', verbose_name='دسته')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='location.location', verbose_name='موقعیت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'آگهی',
                'verbose_name_plural': 'آگهی ها',
            },
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='attribute')),
            ],
        ),
        migrations.CreateModel(
            name='AdvertisementImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم')),
                ('image_file', models.FileField(upload_to='images/advertisement/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'png', 'jpeg'))], verbose_name='عکس')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='advertisement.advertisement', verbose_name='آگهی')),
            ],
        ),
        migrations.CreateModel(
            name='AdvAttrValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, verbose_name='value')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='advertisement.advertisement', verbose_name='advertisement')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='advertisement.attribute', verbose_name='attribute')),
            ],
        ),
    ]
